### ISSUE TITLE
Allow peaceful mode option

### ISSUE THREAD

**Issue by ghost** [SuperSandro2000/AlienPlant#1]
Would be nice to be able to start a farm w/o first needing to kill aliens, so that this mod could be used in a peaceful map.

**Comment by SuperSandro2000** [comment]
That was never the goal for this mod. I wanted to make something where you can play with not a lot of bitter but not without them and still get enough alien artifacts.
I don't realy want to add that so I recommend you to use another mod that adds that (we have a few of them on the forums) or make a recipe yourself. Sorry

**Comment by SuperSandro2000** [comment]
That was never the goal for this mod. I wanted to make something where you can play with not a lot of bitter but not without them and still get enough alien artifacts.
I don't realy want to add that so I recommend you to use another mod that adds that (we have a few of them on the forums) or make a recipe yourself. Sorry
